In [1]:
import pandas as pd

In [2]:
print(dir(pd))

['ArrowDtype', 'BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt8Dtype', '__all__', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_built_with_meson', '_config', '_is_numpy_dev', '_libs', '_pandas_datetime_CAPI', '_pandas_parser_CAPI', '_testing', '_typing', '_version_meson', 'annotations', 'api', 'array', 'arrays', 'bdate_range', 'compat', 'concat', 'core', 'crosstab', 'cut', 'date_range', 'describe_option', 'errors', 'eval', 'factorize', 'from_dummies', 'get_dummies', 'get_option', 'infer_freq', 'interval_range', 'io', 'isna', 'isnull', 'json_normalize', 'lreshape', 'melt', 'merge', 'merge_asof', 'merge_ordered', 'notna', 'notnull', 'offsets', 'option_context', 'options', 'pandas', 'period_range', 'pivot', 'pivot_table', 'plotting', 'qcut', 'read_clipboard', 'read_csv', 'read_excel', 'read_feather', 'read_fwf', 'read_gbq', 'read_hdf', 'read_html', 'read_json', 'read_orc', 'read_parquet', 'read_pickle', 'read_sas', 'read_spss', 'read_sql', 'read_sql_query', 'read_sql_table', 'read_stata', 'read_table', 'read_xml', 'reset_option', 'set_eng_float_format', 'set_option', 'show_versions', 'test', 'testing', 'timedelta_range', 'to_datetime', 'to_numeric', 'to_pickle', 'to_timedelta', 'tseries', 'unique', 'util', 'value_counts', 'wide_to_long']

In [3]:
#loc & ilodc

In [4]:
adani = pd.read_csv(r"C:\Users\ASUS\Downloads\adani.csv")

In [5]:
adani.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63470 entries, 0 to 63469
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   timestamp     63470 non-null  int64
 1   symbol        63470 non-null  object
 2   company       63470 non-null  object
 3   open          40596 non-null  float64
 4   high          40596 non-null  float64
 5   low           40596 non-null  float64
 6   close         40596 non-null  float64
 7   volume        40596 non-null  float64
 8   dividends     40596 non-null  float64
 9   stock_splits  40596 non-null  float64
dtypes: float64(7), int64(1), object(2)
memory usage: 4.8+ MB

In [6]:
adani.describe()

,timestamp,open,high,low,close,volume,dividends,stock_splits
count,6.347000e+04,40596.000000,40596.000000,40596.000000,40596.000000,4.059600e+04,40596.000000,40596.000000
mean,1.389849e+09,437.259328,444.338741,429.325795,436.546910,6.870785e+06,0.014124,0.000296
std,2.127293e+08,656.158667,665.852307,644.581424,654.943367,2.745746e+07,0.462586,0.036471
min,1.025482e+09,-0.011106,-0.011148,-0.010666,-0.011024,0.000000e+00,0.000000,0.000000
25%,1.204157e+09,49.799999,50.895930,48.291898,49.599998,3.120445e+05,0.000000,0.000000
50%,1.389269e+09,132.465404,135.449997,129.242966,132.347427,1.252098e+06,0.000000,0.000000
75%,1.574813e+09,558.857418,568.499850,547.245421,557.947266,4.072442e+06,0.000000,0.000000
max,1.758240e+09,4169.101277,4184.080084,4060.654863,4159.415039,1.210999e+09,58.000000,5.000000

In [7]:
#wp = [i for i in 'python']
#print(wp)

['p', 'y', 't', 'h', 'o', 'n']

In [10]:
adani.loc[0:5,:]

,timestamp,symbol,company,open,high,low,close,volume,dividends,stock_splits
0,1758240000,ACC.NS,ACC Limited,1875.500000,1888.000000,1860.000000,1879.099976,483333.0,0.0,0.0
1,1758240000,ADANIENSOL.NS,Adani Energy Solutions Limited,865.000000,899.000000,855.200012,877.150024,8119554.0,0.0,0.0
2,1758240000,ADANIENT.NS,Adani Enterprises Limited,2495.000000,2579.000000,2466.100098,2524.000000,7965135.0,0.0,0.0
3,1758240000,ADANIGREEN.NS,Adani Green Energy Limited,1025.000000,1071.000000,1003.000000,1030.699951,17650332.0,0.0,0.0
4,1758240000,ADANIPORTS.NS,Adani Ports and Special Economic Zone Limited,1447.800049,1460.000000,1425.000000,1427.800049,8069167.0,0.0,0.0
5,1758240000,ADANIPOWER.NS,Adani Power Limited,135.199997,144.600006,133.070007,141.880005,431620030.0,0.0,0.0

In [14]:
adani.loc[0:4,'symbol']

0           ACC.NS
1    ADANIENSOL.NS
2      ADANIENT.NS
3    ADANIGREEN.NS
4    ADANIPORTS.NS
Name: symbol, dtype: object

In [16]:
adani.loc[0:4,['symbol','open','low']]

          symbol         open          low
0         ACC.NS  1875.500000  1860.000000
1  ADANIENSOL.NS   865.000000   855.200012
2    ADANIENT.NS  2495.000000  2466.100098
3  ADANIGREEN.NS  1025.000000  1003.000000
4  ADANIPORTS.NS  1447.800049  1425.000000

In [17]:
adani.loc[0:4,adani.columns[1:6:2]]

          symbol         open          low
0         ACC.NS  1875.500000  1860.000000
1  ADANIENSOL.NS   865.000000   855.200012
2    ADANIENT.NS  2495.000000  2466.100098
3  ADANIGREEN.NS  1025.000000  1003.000000
4  ADANIPORTS.NS  1447.800049  1425.000000

In [20]:
adani.loc[::2,['symbol','open']] #for even

              symbol         open
0             ACC.NS  1875.500000
2        ADANIENT.NS  2495.000000
4      ADANIPORTS.NS  1447.800049
6       AMBUJACEM.NS   588.000000
8             AWL.NS   264.000000
...              ...          ...
63460  ADANIENSOL.NS          NaN
63462  ADANIGREEN.NS          NaN
63464  ADANIPOWER.NS          NaN
63466        ATGL.NS          NaN
63468        NDTV.NS          NaN

[31735 rows x 2 columns]

In [27]:
acc_df = adani[adani['symbol'] == 'ACC']

In [28]:
acc_table = acc_df.copy()

In [29]:
acc_table

Empty DataFrame
Columns: [timestamp, symbol, company, open, high, low, close, volume, dividends, stock_splits]
Index: []

In [30]:
'open	high	low	close'.split('\t')

['open', 'high', 'low', 'close']

In [32]:
#acc_table.loc[12,'open	high	low	close'.split('\t')]

In [33]:
acc_table

Empty DataFrame
Columns: [timestamp, symbol, company, open, high, low, close, volume, dividends, stock_splits]
Index: []

In [34]:
acc_table.loc[12,'open	high	low	close'.split('\t')] = range(200,204)

In [35]:
acc_table

,timestamp,symbol,company,open,high,low,close,volume,dividends,stock_splits
12,NaN,NaN,NaN,200.0,201.0,202.0,203.0,NaN,NaN,NaN

In [39]:
acc_table.loc[4,'open	high	low	close'.split('\t')] = range(1,5)

In [40]:
acc_table

,timestamp,symbol,company,open,high,low,close,volume,dividends,stock_splits
12,NaN,NaN,NaN,200.0,201.0,202.0,203.0,NaN,NaN,NaN
11,NaN,NaN,NaN,1.0,2.0,3.0,4.0,NaN,NaN,NaN
4,NaN,NaN,NaN,1.0,2.0,3.0,4.0,NaN,NaN,NaN

In [45]:
all_data = acc_table['open	high	low	close'.split('\t')].items()   #t ko tab khte h

In [47]:
next(all_data)

('open',
 12    200.0
 11      1.0
 4       1.0
 Name: open, dtype: float64)

In [48]:
#iloc

In [49]:
adani.iloc[2:5,2:5]

                                         company         open    high
2                      Adani Enterprises Limited  2495.000000  2579.0
3                     Adani Green Energy Limited  1025.000000  1071.0
4  Adani Ports and Special Economic Zone Limited  1447.800049  1460.0

In [52]:
adani.iloc[1:100,1:7]

,symbol,company,open,high,low,close
1,ADANIENSOL.NS,Adani Energy Solutions Limited,865.000000,899.000000,855.200012,877.150024
2,ADANIENT.NS,Adani Enterprises Limited,2495.000000,2579.000000,2466.100098,2524.000000
3,ADANIGREEN.NS,Adani Green Energy Limited,1025.000000,1071.000000,1003.000000,1030.699951
4,ADANIPORTS.NS,Adani Ports and Special Economic Zone Limited,1447.800049,1460.000000,1425.000000,1427.800049
5,ADANIPOWER.NS,Adani Power Limited,135.199997,144.600006,133.070007,141.880005
...,...,...,...,...,...,...
95,ATGL.NS,Adani Total Gas Limited,595.000000,598.200012,592.049988,594.599976
96,AWL.NS,AWL Agri Business Limited,260.600006,262.250000,256.200012,256.899994
97,NDTV.NS,New Delhi Television Limited,112.953087,116.771103,112.953087,114.866066
98,SANGHIIND.NS,Sanghi Industries Limited,64.599998,64.839996,63.750000,63.860001
99,ACC.NS,ACC Limited,1835.099976,1849.699951,1830.000000,1838.300049

In [53]:
adani.iloc[1:4,1:7] = [[1]*6,
                       [2]*6,
                       [3]*6]

In [54]:
adani

,timestamp,symbol,company,open,high,low,close,volume,dividends,stock_splits
0,1758240000,ACC.NS,ACC Limited,1875.500000,1888.000000,1860.000000,1879.099976,483333.0,0.0,0.0
1,1758240000,1,1,1.000000,1.000000,1.000000,1.000000,8119554.0,0.0,0.0
2,1758240000,2,2,2.000000,2.000000,2.000000,2.000000,7965135.0,0.0,0.0
3,1758240000,3,3,3.000000,3.000000,3.000000,3.000000,17650332.0,0.0,0.0
4,1758240000,ADANIPORTS.NS,Adani Ports and Special Economic Zone Limited,1447.800049,1460.000000,1425.000000,1427.800049,8069167.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
63465,1025481600,AMBUJACEM.NS,Ambuja Cements Limited,17.374223,17.759334,17.298463,17.670948,630442.0,0.0,0.0
63466,1025481600,ATGL.NS,Adani Total Gas Limited,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63467,1025481600,AWL.NS,AWL Agri Business Limited,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63468,1025481600,NDTV.NS,New Delhi Television Limited,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63469,1025481600,SANGHIIND.NS,Sanghi Industries Limited,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
adani.iloc[:,[0,-1]]

        timestamp  stock_splits
0      1758240000           0.0
1      1758240000           0.0
2      1758240000           0.0
3      1758240000           0.0
4      1758240000           0.0
...           ...           ...
63465  1025481600           0.0
63466  1025481600           NaN
63467  1025481600           NaN
63468  1025481600           NaN
63469  1025481600           NaN

[63470 rows x 2 columns]